### ISSUE TITLE
simple example of using this vega format loader with Chicago crimes data

### ISSUE THREAD

**Issue by RandomFractals** [vega/vega-loader-arrow#7]
see if you'd like to include it in your readme or docs for this lib:

https://observablehq.com/@randomfractals/chicago-crimes-arrow-data-vega-viz

I think it beats the scrabble example since it's all real-world data.

Also, great job on this library! It performs really well!

I just had to take it for a spin :)

**Comment by domoritz** [comment]
This is great. Can you send a PR to add this example to the readme?

**Comment by RandomFractals** [comment]
@domoritz I'd love to, but I don't know where you'd want to stick it in readme or online docs coming for this lib. I'd rather leave it up to you, if you don't mind.

**Comment by RandomFractals** [comment]
that was fast! :) 

Thank you guys for this lib & adding my works on Chi crimes with VL & real-world arrow data to your readme.

🤗
