### ISSUE TITLE
Feather support?

### ISSUE THREAD

**Issue by mands** [vega/vega-loader-arrow#9]
Hi there,

Just wondering if this library supports Feather files in addition to raw `.arrow` files, and if not if there are any plans to add support for them?

Cheers!

**Comment by xhochy** [comment]
Supporting Feather is probably no good idea. The Arrow files are more powerful in functionality (they are a strict superset) and Feather as a format should be considered deprecated now that there is also a fully maintained R-arrow package/binding.

**Comment by mands** [comment]
Got it - thanks! Probably not the right place to ask but then is the Arrow format now considered stable enough to use in place of Feather?

**Comment by xhochy** [comment]
As the Arrow format is the backing format also of Feather, Arrow files are as stable as Feather files. Both are only stable enough for active data exchange. For long-term storage, you should use Apache Parquet or similar (this is supported by most Arrow implementations).

**Comment by domoritz** [comment]
It sounds like we don't actually want feather support. I would also suggest a separate plugin for other data formats to keep the code lean.

**Comment by mands** [comment]
Great - thanks for the info
